### ISSUE TITLE
What does it run on?

### ISSUE THREAD

**Issue by clort81** [VictorGhys/2DAE08_ghys_victor_qbert#1]
What are the build and execution requirements?

**Comment by VictorGhys** [comment]
The project consists out of two parts: Minigin (game engine) as a static library and Qbert (game) as Aplication .exe.
Steps to run:
-clone project
-open .sln in visual studio
-set Qbert as Startup Project
-build and run

**Comment by clort81** [comment]
Thank you.  Closing.
